import me.modmuss50.mpp.ReleaseType
import net.fabricmc.loom.task.RemapJarTask

plugins {
	id("server_stats.module")
	alias(libs.plugins.mod.publish)
}

dependencies {
	include(project(":module:api"))
	include(project(":module:impl"))

	include(project(":module:broadcast:client:1.0.0-beta.1.5.0-to-1.3.0-alpha.12w16a"))
	include(project(":module:broadcast:client:1.3.0-alpha.12w17a-to-1.3.0-alpha.12w17a"))
	include(project(":module:broadcast:merged"))
	include(project(":module:broadcast:server"))

	include(project(":module:bugfix:achievement:adventuring-time-unlock"))
	include(project(":module:bugfix:achievement:adventuring-time-persistence"))
	include(project(":module:bugfix:achievement:overkill:1.0.0-beta.1.9.0-pre.5-to-1.1.0-alpha.11w48a"))
	include(project(":module:bugfix:achievement:overkill:1.1.0-alpha.11w49a-to-1.6.0-alpha.13w25c"))
	include(project(":module:bugfix:achievement:overkill:1.6.0-alpha.13w26a-to-1.8.0-alpha.14w31a"))
	include(project(":module:bugfix:achievement:sniper-duel:1.0.0-beta.1.8.0-pre.1-to-1.0.0-beta.1.8.0-pre.1"))
	include(project(":module:bugfix:achievement:sniper-duel:1.0.0-beta.1.8.0-pre.2-to-1.1-alpha.12w01a"))
	include(project(":module:bugfix:achievement:the-end"))
	include(project(":module:bugfix:achievement:tool-material:1.0.0-beta.1.5.0-to-1.3.2"))
	include(project(":module:bugfix:achievement:tool-material:1.4.0-alpha.12w32a-to-1.6.4"))
	include(project(":module:bugfix:achievement:tool-material:1.7.0-alpha.13w36a-to-1.7.0-alpha.13w36b"))

	include(project(":module:bugfix:misc:game-directory"))

	include(project(":module:bugfix:statistic:block-merging:1.0.0-beta.1.5.0-to-1.6.4"))
	include(project(":module:bugfix:statistic:block-merging:1.7.0-alpha.13w36a-to-1.12.2"))
	include(project(":module:bugfix:statistic:combat:1.7.0-alpha.13w36a-to-1.8.0-alpha.14w08a"))
	include(project(":module:bugfix:statistic:combat:1.8.0-alpha.14w10a-to-1.8.2-pre.4"))
	include(project(":module:bugfix:statistic:combat:1.8.2-pre.5-to-1.9.0-alpha.15w32c"))
	include(project(":module:bugfix:statistic:combat:1.9.0-alpha.15w33a-to-1.10.2"))
	include(project(":module:bugfix:statistic:combat:1.11.0-alpha.16w32a-to-1.12.0-alpha.17w06a"))
	include(project(":module:bugfix:statistic:combat:1.12.0-alpha.17w13a-to-1.12.0-alpha.17w13b"))
	include(project(":module:bugfix:statistic:combat:1.12.0-alpha.17w14a-to-1.12.2"))
	include(project(":module:bugfix:statistic:damage-attribution:1.9.0-alpha.15w36a-to-1.11.0-alpha.16w42a"))
	include(project(":module:bugfix:statistic:damage-attribution:1.11.0-alpha.16w43a-to-1.11.0-alpha.16w43a"))
	include(project(":module:bugfix:statistic:damage-attribution:1.11.0-alpha.16w44a-to-1.12.2"))
	include(project(":module:bugfix:statistic:doubled-distance"))
	include(project(":module:bugfix:statistic:downwards-climbing"))
	include(project(":module:bugfix:statistic:drop-amount:1.0.0-beta.1.5.0-to-1.2.0-alpha.12w08a"))
	include(project(":module:bugfix:statistic:drop-amount:1.2.0-to-1.7.0-alpha.13w37b"))
	include(project(":module:bugfix:statistic:drop-amount:1.7.0-alpha.13w38a-to-1.8.0-alpha.14w08a"))
	include(project(":module:bugfix:statistic:drop-amount:1.8.0-alpha.14w10a-to-1.8.0-alpha.14w28b"))
	include(project(":module:bugfix:statistic:drop-amount:1.8.0-alpha.14w29a-to-1.12.2"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.5.0-to-1.0.0-beta.1.7.3"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.8.0-pre.1-to-1.0.0-beta.1.8.1"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.9.0-pre.1-to-1.0.0-beta.1.9.0-pre.1"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.9.0-pre.2-to-1.0.0-beta.1.9.0-pre.2"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.9.0-pre.3-to-1.0.0-beta.1.9.0-pre.3"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.9.0-pre.4-to-1.0.0-beta.1.9.0-pre.5"))
	include(project(":module:bugfix:statistic:item-use:1.0.0-beta.1.9.0-pre.6-to-1.1.0"))
	include(project(":module:bugfix:statistic:item-use:1.2.0-alpha.12w03a-to-1.2.0-alpha.12w03a"))
	include(project(":module:bugfix:statistic:item-use:1.2.0-alpha.12w04a-to-1.3.0-alpha.12w16a"))
	include(project(":module:bugfix:statistic:item-use:1.3.0-alpha.12w17a-to-1.4.0-alpha.12w32a"))
	include(project(":module:bugfix:statistic:item-use:1.4.0-alpha.12w34a-to-1.4.0-alpha.12w36a"))
	include(project(":module:bugfix:statistic:item-use:1.4.0-alpha.12w37a-to-1.4.7"))
	// Only LilyPadItemMixin breaks here, even tho the generated bytecode seems identical ...
	include(project(":module:bugfix:statistic:item-use:1.5.0-alpha.13w01a-to-1.6.4"))
	include(project(":module:bugfix:statistic:item-use:1.7.0-alpha.13w36a-to-1.8.0-alpha.14w08a"))
	include(project(":module:bugfix:statistic:item-use:1.9.0-alpha.15w33c-to-1.11.0"))
	include(project(":module:bugfix:statistic:item-use:1.11.1-alpha.16w50a-to-1.12.2"))
	include(project(":module:bugfix:statistic:jump"))
	include(project(":module:bugfix:statistic:movement"))
	include(project(":module:bugfix:statistic:pickup-amount:1.9.0-alpha.15w33a-to-1.12.0-alpha.17w06a"))
	include(project(":module:bugfix:statistic:pickup-amount:1.12.0-alpha.17w13a-to-1.12.2"))
	include(project(":module:bugfix:statistic:result-amount"))
	include(project(":module:bugfix:statistic:sheep-shearing:1.0.0-beta.1.7.0-to-1.5.2"))
	include(project(":module:bugfix:statistic:sheep-shearing:1.6.0-alpha.13w16a-to-1.6.4"))
	include(project(":module:bugfix:statistic:sheep-shearing:1.7.0-alpha.13w36a-to-1.8.9"))
	include(project(":module:bugfix:statistic:sheep-shearing:1.9.0-alpha.15w31a-to-1.10.2"))
	include(project(":module:bugfix:statistic:sheep-shearing:1.11.0-alpha.16w32a-to-1.12.2"))

	include(project(":module:compat:modmenu"))

	include(project(":module:dfu"))

	include(project(":module:entrypoint:client"))
	include(project(":module:entrypoint:common"))
	include(project(":module:entrypoint:merged:1.3.2-to-1.5.2"))
	include(project(":module:entrypoint:merged:1.6.0-alpha.13w16a-to-1.6.4"))
	include(project(":module:entrypoint:server"))

	include(project(":module:event"))

	include(project(":module:gui:large-stats:1.0.0-beta.1.5.0-to-1.2.3"))
	include(project(":module:gui:large-stats:1.2.4-to-1.5.2"))
	include(project(":module:gui:large-stats:1.6.0-alpha.13w16a-to-1.6.4"))

	include(project(":module:gui:mob-stats:1.0.0-beta.1.5.0-to-1.5.2"))
	include(project(":module:gui:mob-stats:1.6.0-alpha.13w16a-to-1.6.4"))

	include(project(":module:gui:util:1.0.0-beta.1.5.0-to-1.0.0-beta.1.9.0-pre.4"))
	include(project(":module:gui:util:1.0.0-beta.1.9.0-pre.5-to-1.3.0-alpha.12w17a"))
	include(project(":module:gui:util:1.3.2-to-1.5.2"))
	include(project(":module:gui:util:1.6.0-alpha.13w16a-to-1.6.0-alpha.13w17a"))
	include(project(":module:gui:util:1.6.0-alpha.13w18a-to-1.6.0-alpha.13w23b"))
	include(project(":module:gui:util:1.6.0-alpha.13w24a-to-1.6.4"))

	include(project(":module:identity:client:0.31.20100327-to-0.31.20100625-1917"))
	include(project(":module:identity:client:0.31.20100627-to-1.3-alpha.12w17a"))
	include(project(":module:identity:merged:1.3.2-to-1.5.2"))
	include(project(":module:identity:merged:1.6.0-alpha.13w16a-to-1.6.4"))
	include(project(":module:identity:merged:1.7.0-alpha.13w36a-to-1.7.0-alpha.13w38c"))
	include(project(":module:identity:merged:1.7.0-alpha.13w39a-to-1.7.5"))
	include(project(":module:identity:server"))

	include(project(":module:lifecycle:client:0.31.20100327-to-0.31.20100330-1611"))
	include(project(":module:lifecycle:client:0.31.20100413-to-0.31.20100625-1917"))
	include(project(":module:lifecycle:client:0.31.20100627-to-1.0.0-alpha.1.0.5"))
	include(project(":module:lifecycle:client:1.0.0-alpha.1.0.6-to-1.0.0-alpha.1.1.2"))
	include(project(":module:lifecycle:client:1.0.0-alpha.1.2.0-to-1.0.0-beta.1.2.0"))
	include(project(":module:lifecycle:client:1.0.0-beta.1.3.0-to-1.0.0-beta.1.7.3"))
	include(project(":module:lifecycle:client:1.0.0-beta.1.8.0-pre.1-to-1.3.0-alpha.12w17a"))

	include(project(":module:lifecycle:merged:1.3.2-to-1.4.0-alpha.12w38b"))
	include(project(":module:lifecycle:merged:1.4.0-alpha.12w39a-to-1.5.2"))
	include(project(":module:lifecycle:merged:1.6.0-alpha.13w16a-to-1.6.4"))

	include(project(":module:lifecycle:server:1.0.0-alpha.0.1.0-to-1.0.0-beta.1.2.0"))
	include(project(":module:lifecycle:server:1.0.0-beta.1.3.0-to-1.0.0-beta.1.3.0"))
	include(project(":module:lifecycle:server:1.0.0-beta.1.4.0-to-1.1.0-alpha.11w50a"))
	include(project(":module:lifecycle:server:1.1.0-alpha.12w01a-to-1.3.0-alpha.12w17a"))

	include(project(":module:network:osl:client"))
	include(project(":module:network:osl:common"))
	include(project(":module:network:osl:server"))

	include(project(":module:network:vanilla:client"))
	include(project(":module:network:vanilla:common"))
	include(project(":module:network:vanilla:merged:1.3.2-to-1.5.2"))
	include(project(":module:network:vanilla:merged:1.6.0-alpha.13w16a-to-1.6.4"))
	include(project(":module:network:vanilla:server"))

	include(project(":module:provider:client:0.31.20100327-to-0.31.20100625-1917"))
	include(project(":module:provider:client:0.31.20100627-to-1.0.0-alpha.1.0.5"))
	include(project(":module:provider:client:1.0.0-alpha.1.0.6-to-1.0.0-beta.1.4.0"))
	include(project(":module:provider:client:1.0.0-beta.1.5.0-to-1.3-alpha.12w17a"))
	include(project(":module:provider:common:0.31.20100327-to-1.0.0-beta.1.4.0"))
	include(project(":module:provider:common:1.0.0-beta.1.5.0-to-1.3-alpha.12w17a"))
	include(project(":module:provider:merged"))
	include(project(":module:provider:server"))

	include(project(":module:statistic:combat:1.0.0-beta.1.5.0-to-1.1.0-beta.1.7.3"))
	include(project(":module:statistic:combat:1.0.0-beta.1.8.0-pre.1-to-1.1.0-alpha.11w48a"))
	include(project(":module:statistic:combat:1.1.0-alpha.11w49a-to-1.1.0-alpha.11w50a"))
	include(project(":module:statistic:combat:1.1.0-alpha.12w01a-to-1.6.4"))

	include(project(":module:statistic:item-transfer:1.0.0-beta.1.5.0-to-1.2.0-alpha.12w08a"))
	include(project(":module:statistic:item-transfer:1.2.0-to-1.6.4"))
	include(project(":module:statistic:item-transfer:1.7.0-alpha.13w36a-to-1.7.0-alpha.13w37b"))
	include(project(":module:statistic:item-transfer:1.7.0-alpha.13w38a-to-1.8.0-alpha.14w05b"))
	include(project(":module:statistic:item-transfer:1.8.0-alpha.14w06a-to-1.8.0-alpha.14w08a"))
	include(project(":module:statistic:item-transfer:1.8.0-alpha.14w10a-to-1.8.0-alpha.14w26c"))
	include(project(":module:statistic:item-transfer:1.8.0-alpha.14w27a-to-1.8.0-alpha.14w28b"))
	// NOTE: Maybe split on 1.8.2-pre.4 / 1.8.2-pre.5
	// IdRegistry changes here to actually be generic, and not return Object
	include(project(":module:statistic:item-transfer:1.8.0-alpha.14w29a-to-1.9.0-alpha.15w32c"))
	include(project(":module:statistic:item-transfer:1.9.0-alpha.15w33a-to-1.12.0-alpha.17w06a"))
	include(project(":module:statistic:item-transfer:1.12.0-alpha.17w13a-to-1.12.2"))

	include(project(":module:statistic:local:client"))
	include(project(":module:statistic:local:merged"))
	include(project(":module:statistic:local:server"))

	include(project(":module:statistic:movement"))

	include(project(":module:translation:client"))
	include(project(":module:translation:common"))
	include(project(":module:translation:merged"))
	include(project(":module:translation:server"))

	include(project(":module:util"))
}

tasks.withType<Jar> {
	from("LICENSE")
}

val modVersion = project.property("mod_version").toString()

fun getVersionType(): ReleaseType {
	return if (modVersion.startsWith("0.") || modVersion.contains("-alpha.")) {
		ReleaseType.ALPHA
	} else if (modVersion.contains("-")) {
		ReleaseType.BETA
	} else {
		ReleaseType.STABLE
	}
}

publishMods {
	version = modVersion
	displayName = "v${modVersion}"

	type = getVersionType()
	modLoaders.addAll("ornithe")

	file = tasks.withType<RemapJarTask>()["remapJar"].archiveFile
	changelog = file(rootDir.toPath().resolve("src/main/resources/changelog/${modVersion}.md")).readText()

	modrinth {
		accessToken = providers.environmentVariable("MODRINTH_SECRET")
		projectId = "shTz7pFB"

		minecraftVersionRange {
			start = "b1.5"
			end = "1.2.5"
			// end = "12w17a" - missing on Modrinth!
			includeSnapshots = true
		}

		minecraftVersionRange {
			start = "1.3.2"
			end = "1.12.2"
			includeSnapshots = true
		}

		optional("modmenu-ornithe")

		optional {
			slug = "osl"
			version = libs.versions.osl.bundle.get()
		}

		incompatible("achievement-fix")
	}
}
