name: build-java
on: [ push, pull_request ]

jobs:
  build:
    runs-on: lostluma-linux-docker
    steps:
      - name: checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: restore jdk installations
        uses: https://code.forgejo.org/actions/cache/restore@v4
        with:
          path: |
            /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk
          key: ${{ runner.os }}-java
      - name: setup jdk
        uses: https://github.com/actions/setup-java@v4
        with:
          java-version: |
            8
            21
          distribution: temurin
      - name: restore cached dependencies
        uses: https://code.forgejo.org/actions/cache/restore@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle
      - name: install workarounds
        run: ./workaround/broken-manifest.sh
      - name: build
        run: ./gradlew build --no-daemon --warning-mode=all
      - name: capture build artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: server-stats-artifacts.zip
          path: build/libs
          if-no-files-found: error
      - name: cache downloaded dependencies
        if: ${{ github.ref_name == 'stardust' && !cancelled() }}
        uses: https://code.forgejo.org/actions/cache/save@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle
      - name: cache jdk installations
        if: ${{ github.ref_name == 'stardust' && !cancelled() }}
        uses: https://code.forgejo.org/actions/cache/save@v4
        with:
          path: |
            /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk
          key: ${{ runner.os }}-java
