[versions]
gson = "2.10.1"
slf4j = "2.0.17"
annotations = "26.0.2"
fabric_loader = "0.17.0+local"

ploceus = "1.10.16"
fabric_loom = "1.10.5"

mod_publish = "0.8.4"

modmenu = "0.3.1+mcb1.7.3"

osl_bundle = "0.12.1"
osl_networking_server = "0.8.0+server-mcb1.5-mc11w48a"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

ploceus = { module = "net.ornithemc:ploceus", version.ref = "ploceus" }
fabric_loom = { module = "net.fabricmc:fabric-loom", version.ref = "fabric_loom" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
osl_networking_server = { module = "net.ornithemc.osl:networking", version.ref = "osl_networking_server" }

[plugins]
mod_publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod_publish" }
